- Cargo.toml
webpki 0.9.2 depends on *ring* 0.6.3, which contains a possible
security fix.
> Require webpki 0.9.2; bump version to 0.6.1.

- Cargo.toml
This makes it easier to for webpki-roots-based projects (especially Rustls-based projects) to upgrade to *ring* 0.7.
> Update webpki dependency to 0.10.

- Cargo.toml
This is required in order to update Rustls to use *ring* 0.9.
> 0.10.0: Use webpki 0.12.

- src/lib.rs
Re-running `build.py` removes some certificates, as Mozilla have removed them, e.g.
* https://bugzilla.mozilla.org/show_bug.cgi?id=1420855
* https://bugzilla.mozilla.org/show_bug.cgi?id=1410544
> Some CAs have been removed

- Cargo.toml
- src/bin/process_cert.rs
- src/lib.rs
webpki contains breaking API changes. The one that affects webpki-roots is
the change to use Rust naming conventions.
> 0.22.0: Upgrade to webpki 0.22.0.

- .github/dependabot.yml
- .github/workflows/build.yml
To address [a pending deprecation](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/), and to remove CI warnings this branch brings the CI improvements that landed on the rustls/rustls repo in https://github.com/rustls/rustls/pull/1214 to this repo.
This commit updates the existing .github/dependabot.yml config that monitors Cargo dependencies to also monitor GitHub actions (on a weekly cadence).
Does what it says on the tin.
This commit replaces the actions-rs/toolchain action with dtolnay/rust-toolchain. The former is [no longer maintained](https://github.com/actions-rs/toolchain/issues/216).
> CI: update workflow actions

- Cargo.toml
- tests/verify.rs
This is a follow up to https://github.com/rustls/webpki-roots/pull/39 that adds a basic integration test for trust anchors in webpki-roots with name constraints.
The general idea is that for each name constraints extension we:
* parse the name constraints with x509-parser, verifying that the encoding is well formed and contains something approximating what we expect (e.g. at least one permitted subtree, no excluded subtrees).
* convert the name constraints into the form rcgen expects for certificate generation parameters.
* issue our own trust anchor CA certificate with the name constraints from the webpki trust anchor.
* for each permitted subtree base dns name in the name constraints we use our generated CA to issue end entity certificates that will be permitted, and rejected by the …
> tests: add name constraints integration test.

- Cargo.toml
- tests/verify.rs
> Move to pki-types 0.2.1

- src/lib.rs
- tests/codegen.rs
the crate does not rely on libstd API so it's already no-std compatible. it only needs the `#![no_std]` attribute.
> add no-std support

- src/lib.rs
I think we should backport this to a 0.25.3 release?
> Refresh certificates

- Cargo.toml
- src/lib.rs
This branch targets the `rel-0.25` branch, which was branched from 22702f5e206604890349983f9c334dbc244d6f18, the last commit on `main` that's semver compatible with the `0.25.2` release cut from 4730449082b71d0a4f704b9180711e4d03995fc2. It backports the CCADB trust root updates from https://github.com/rustls/webpki-roots/pull/52 to prepare v0.25.3
New trust anchors:
* [CommScope Public Trust RSA Root-01](https://bugzilla.mozilla.org/show_bug.cgi?id=1763177)
* [CommScope Public Trust RSA Root-02](https://bugzilla.mozilla.org/show_bug.cgi?id=1763177)
* [CommScope Public Trust ECC Root-01](https://bugzilla.mozilla.org/show_bug.cgi?id=1763177)
* [CommScope Public Trust ECC Root-02](https://bugzilla.mozilla.org/show_bug.cgi?id=1763177)
* [TrustAsia Global Root CA …
> v0.25.3 release preparation

- Cargo.toml
- tests/codegen.rs
- tests/verify.rs
We will actually want to merge this as there are incompatible changes in the dev-dependencies.
> Upgrade to (moved ServerName) alpha releases

- Cargo.toml
Proposed release notes:
* **Improving API stability.** This crate now uses types from [rustls-pki-types](https://crates.io/crates/rustls-pki-types); we expect this to reduce the number of breaking changes in rustls ecosystem.
* **`no_std` support.**
> Prepare 0.26.0

- webpki-roots/Cargo.toml
- webpki-roots/src/lib.rs
See https://bugzilla.mozilla.org/show_bug.cgi?id=1870673
Removals:
1. SECOM Trust.net - Security Communication RootCA1
This expired root CA was removed upstream.
See https://bugzilla.mozilla.org/show_bug.cgi?id=1865450
Additions:
1. Telekom Security TLS ECC Root 2020
See https://bugzilla.mozilla.org/show_bug.cgi?id=1820592
2. Telekom Security TLS RSA Root 2023
See https://bugzilla.mozilla.org/show_bug.cgi?id=1820592
> process upstream February root updates

- Cargo.toml
- src/lib.rs
This branch targets the base branch `rel-0.25` to prepare a v0.25.4 point release in the 0.25.x release stream with the upstream February Mozilla trusted root updates from https://github.com/rustls/webpki-roots/pull/60
Removals:
1. SECOM Trust.net - Security Communication RootCA1
This expired root CA was removed upstream.
See https://bugzilla.mozilla.org/show_bug.cgi?id=1865450
Additions:
1. Telekom Security TLS ECC Root 2020
See https://bugzilla.mozilla.org/show_bug.cgi?id=1820592
2. Telekom Security TLS RSA Root 2023
See https://bugzilla.mozilla.org/show_bug.cgi?id=1820592
> Prepare 0.25.4, process upstream February root updates

- README.md
- webpki-roots/src/lib.rs
- webpki-roots/tests/codegen.rs
* Remove some duplicated content from the top-level README
* Update the webpki-roots rustdoc to recommend rustls-platform-verifier instead of rustls-native-certs
* Port the recommendation/warning from rustdoc to the top-level README
> Small documentation updates

- webpki-roots/src/lib.rs
This is the "Common Name or Certificate Name" changing for some certificates, and now matches the common name in these cases.
No code change; no need to make a release.
> Accept upstream changes in CCADB metadata

- webpki-roots/Cargo.toml
- webpki-roots/src/lib.rs
Processes latest upstream CCADB Mozilla trusted root updates.
Additions:
"FIRMAPROFESIONAL CA ROOT-A WEB"
See https://bugzilla.mozilla.org/show_bug.cgi?id=1889671
**New trust anchors:**
[FIRMAPROFESIONAL CA ROOT-A WEB](https://bugzilla.mozilla.org/show_bug.cgi?id=1889671)
> Prepare 0.26.2, add FIRMAPROFESIONAL CA ROOT-A WEB

- webpki-ccadb/src/lib.rs
This commit update the CCADB codegen to consider any root CA with a distrust for TLS after date as not trusted, irrespective of the distrust date.
The rustls/webpki ecosystem this crate supports does not have the capability to enforce a "active distrust" of a TLS trust anchor in the Mozilla root program that has a "Distrust for TLS After Date" date in CCADB. Given this constraint we choose to remove roots immediately when they are given a distrust after date. This is _more_ aggressive than the Mozilla root program but requires no new features implemented in downstream crates. Users needing more nuanced root program enforcement should consider using the rustls-platform-verifier crate.
Updates https://github.com/rustls/webpki-roots/issues/72 (_not yet closing, because the CCADB distrust …
> webpki-ccadb: distrust any CA with a distrust after date

- webpki-roots/Cargo.toml
- webpki-roots/src/lib.rs
This CA is being distrusted by the Mozilla root program for TLS certificates issued after 2024.06.30.
Because `webpki-roots` can't express this distrust after date without breaking changes, and because the extant trusted certificates by this CA number less than 100, we choose to distrust the trust anchor in webpki-roots immediately and without any further qualification.
See [the MDSP announcement post](https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/XpknYMPO8dI/m/JBNFg3aVAwAJ), and [this bugzilla bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1901080) for more information.
Resolves https://github.com/rustls/webpki-roots/issues/72
* [GLOBALTRUST 2020 CA](https://bugzilla.mozilla.org/show_bug.cgi?id=1901080) has been removed due to a prolonged pattern of operational and …
> 0.26.3 release preparation, GLOBALTRUST 2020 removal

- webpki-root-certs/Cargo.toml
- webpki-roots/Cargo.toml
Since the 0.26.3 release has already been tagged before the `webpki-roots-crate` existed I think it makes sense to bump the version for the first `webpki-roots-crate` release. We will not publish the `webpki-roots` 0.26.4 release since it's identical to 0.26.3.
* New `webpki-root-certs` crate. This crate is similar to `webpki-roots`, but for use with other projects that require the full self-signed X.509 certificate for each trusted root. This is unnecessary overhead for `webpki` and `rustls` and you should prefer using `webpki-roots` for these projects.
> webpki-root-certs 0.26.4 release

- webpki-ccadb/src/lib.rs
Per Chris Clements' [update to the mailing list](https://groups.google.com/a/ccadb.org/g/public/c/VXfaU1_OaHE/m/58V-lTXVAQAJ)
> We recommend users review their linked bookmarks, automation scripts, integration programs, or similar and:
>
> Change their references to public report URLs
>
> from:
>  ccadb-public.secure.force.com (non-enhanced)
>  ccadb-public.force.com (non-enhanced)
> to:
>  ccadb.my.salesforce-sites.com (enhanced)
> webpki-ccadb: update Moz CCADB root report url

- LICENSE-MPL
- README.md
- webpki-root-certs/Cargo.toml
- webpki-root-certs/LICENSE
- webpki-root-certs/LICENSE-APACHE
- webpki-root-certs/LICENSE-MIT
- webpki-roots/Cargo.toml
- webpki-roots/LICENSE
- webpki-roots/LICENSE-APACHE
- webpki-roots/LICENSE-MIT
These crates mistakenly had license files included for Apache and MIT licenses. Both are derived works under an MPL 2.0 license
Resolves https://github.com/rustls/webpki-roots/issues/79
> webpki-roots/webpki-root-certs: prepare 0.26.6, fix license data

- webpki-roots/src/lib.rs
- webpki-roots/tests/codegen.rs
copy-pasting the main usage example produces a clippy warning suggesting this instead
> docs(webpki-roots): simplify usage example

- webpki-ccadb/src/lib.rs
Previously we took the aggressive stance of removing a root as soon as it was described in CCADB as having a distrust for TLS after date. There's [a good argument](https://sslmate.com/blog/post/entrust_distrust_more_disruptive_than_intended) that this is more disruptive than helpful.
Instead, remove roots with a distrust after date only once that date plus a grace period of 398 days has past. The grace period is equal to the maximum allowable subscriber certificate lifetime based on the CA/Browser Forum's baseline requirements.
Since we also want to apply some simple local policy to exclude roots unconditionally a simple block list based on the CCADB SHA256 fingerprint is also added to override the above logic to exclude a root when required.
One FP for the GLOBALSIGN 2020 root is added …
> webpki-ccadb: rework TLS distrust after handling

- .github/workflows/build.yml
We already do this in most of the other Rustls crates, and Zizmor 0.7.0 [flags its absence](https://woodruffw.github.io/zizmor/audits/#artipacked) in this repo. As mentioned in the description of this finding:
> By default, using [actions/checkout](https://github.com/actions/checkout) causes a credential to be persisted in the checked-out repo's .git/config, so that subsequent git operations can be authenticated.
> 
> Subsequent steps may accidentally publicly persist .git/config, e.g. by including it in a publicly accessible artifact via [actions/upload-artifact](https://github.com/actions/upload-artifact).
>
> However, even without this, persisting the credential in the .git/config is non-ideal unless actually needed.
We don't need it, so turn it off :-)
> ci: use persist-credentials: false throughout

- webpki-ccadb/src/lib.rs
See https://github.com/rustls/webpki-roots/actions/runs/13998435097/attempts/1
This has now fixed itself -- https://github.com/rustls/webpki-roots/actions/runs/13998435097/attempts/2 -- so there is no pressing need to land this.
> Support code-signing trust bit

- webpki-root-certs/Cargo.toml
- webpki-roots/Cargo.toml
This picks up the license changed we made; no upstream changes.
Release notes:
The license of the `webpki-roots` and `webpki-root-certs` crates changed from MPL-2.0 to CDLA-Permissive-2.0. Thank you to the [CCADB maintainers for enabling us to make this change](https://github.com/mozilla/www.ccadb.org/issues/188).
*None*
> webpki-(roots|root-certs): v0.26.8 -> v0.26.9

- .github/workflows/build.yml
- webpki-root-certs/Cargo.toml
- webpki-roots/Cargo.toml
This PR rubber stamps 0.26.10 as 1.0.0 with no changes.
After we merge this and release it, we can then:
- Branch rel-0.26
- Open a PR for landing https://github.com/rustls/webpki-roots/commit/c98a20d52e7ba6661ea48e1cbb47f379da46a38f or similar there.
- Release 0.26.11.
This would be the final 0.26 release, and AIUI means people continuing to depend on `webpki-roots = "0.26"` will get all future 1.0 releases.
> Prepare 1.0.0

- Cargo.lock
- Cargo.toml
- webpki-roots/tests/verify.rs
Make sure to update past https://rustsec.org/advisories/RUSTSEC-2025-0047.html.
> Update semver-compatible dependencies
